# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('turno', models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Noturno', 'Noturno'), ('Extra', 'Extra')], default='Matutino', max_length=50)),
            ],
            options={
                'verbose_name': 'Escala',
                'verbose_name_plural': 'Escalas',
            },
        ),
        migrations.CreateModel(
            name='FuncEscala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='frequencia.Escala')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('cpf', models.CharField(max_length=11)),
                ('cargo', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
        migrations.CreateModel(
            name='Justificativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('justificativa', models.CharField(max_length=255)),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atrasados', to='frequencia.Funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TimeField()),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Saida', 'Saida')], default='Entrada', max_length=50)),
                ('maquina', models.CharField(max_length=50)),
                ('consistente', models.BooleanField()),
                ('chefe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chefes', to='frequencia.Funcionario')),
                ('escalaFunc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frequencia', to='frequencia.FuncEscala')),
            ],
        ),
        migrations.AddField(
            model_name='justificativa',
            name='ponto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='frequencia.Ponto'),
        ),
        migrations.AddField(
            model_name='funcescala',
            name='funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='frequencia.Funcionario'),
        ),
    ]
